name: geomap_base_workflow

on:
  push:
    branches: [ "main", "feature/ci_enchancements" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_example:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      SOLUTION_NAME: "MapWpfApplication.sln"                         # Replace with your solution name, i.e. MyWpfApp.sln.
      DOTNET_VERSION: '5.0.301'                                    # The .NET SDK version to use

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '4.0.x'
    
      - name: Print Hello world
        run: |
          echo "Hello, world!"
          echo "DOTNET_VERSION: ${{ env.DOTNET_VERSION }}"
          Get-Location
          
      - name: Clone repo
        uses: actions/checkout@v3
        
      - name: Get all files
        run: |
          Set-Location -Path src
          dir
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build 
        run: |
          Set-Location -Path src
          dir
          msbuild MapWpfApplication.sln /p:Configuration=Release
          
